###
POST localhost:8080/recommend
Content-Type: application/json

{
  "email": "baggomsoon96",
  "type": "TIER",
  "query": {
    "minTier": 12,
    "maxTier": 12
  }
}

###
POST localhost:8080/recommend/study
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJyb2xlIjoiUk9MRV9VU0VSIiwiaXNzIjoiYm9qLXJlY29tbWVuZCIsImV4cCI6MTY3MDE2NDg4NCwiaWF0IjoxNjcwMTYzMDg0LCJlbWFpbCI6ImpjaG05ODQ2IiwibWVtYmVySWQiOiJlMWY1NjQwOC1mZWYzLTRlNjQtYjZkYy0xZWZkMDhkYTJiNGYifQ.yyXiXP3bN_WxQSivG3uTFRua28W6pqxHae9xvvoeWOoPrwbq4-8s0eTEnNjZnlT1rT34H1WWTuo0e0RMOqWPTQ
Content-Type: application/json

{
  "study": "1ee72417-fea2-2ff3-4a80-dac3d075b046",
  "hash": "1234",
  "type": "TIER",
  "query": {
    "minTier": 11,
    "maxTier": 11
  }
}

