### 1. 과제 전체 조회
GET http://localhost:8080/assignment

### 2. 스터디에게 과제 할당
POST http://localhost:8080/assignment/study
Content-Type: application/json

{
  "studyId": "1ee72417-fea2-2ff3-4a80-dac3d075b046",
  "hash": "1234",
  "problemId": 11103
}





